version: '3'

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/24

services:
  redis:
    image: docker.io/bitnami/redis:6.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    #ports:
    #  - '6379:6379'
    expose:
      - "6379"
    volumes:
      - 'redis_data:/bitnami/redis/data'
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2
  asgard-bivrost:
    build:
      context: $GOPATH/src/asgard-bivrost
      dockerfile: $GOPATH/src/asgard-bivrost/Dockerfile
    image: asgard-bivrost
    working_dir: /app
    environment:
     - APP_REGISTRY_ADDR=redis:6379
     - APP_REGISTRY_PASSWORD=
     - APP_PORT=9000
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    depends_on:
      - "redis"
  asgard-service-example:
    build:
       context: .
       dockerfile: Dockerfile
    image: asgard-service-example
    working_dir: /app
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
    depends_on:
      - "redis"

volumes:
  redis_data:
    driver: local
