version: '3'

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/24

services:
  redis:
    image: docker.io/bitnami/redis:6.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    #ports:
    #  - '6379:6379'
    expose:
      - "6379"
    volumes:
      - 'redis_data:/bitnami/redis/data'
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2
  asgard-bivrost:
    build:
      context: /usr/local/go/src/asgard-bivrost
      dockerfile: /usr/local/go/src/asgard-bivrost/Dockerfile
    image: asgard-bivrost
    working_dir: /app
    environment:
     - APP_REGISTRY_ADDR=redis:6379
     - APP_REGISTRY_PASSWORD=
     - APP_PORT=9000
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    depends_on:
      - "redis"
  asgard-service-example:
    build:
       context: .
       dockerfile: Dockerfile
       args:
         GITHUB_USERNAME: ${GITHUB_USERNAME}
         GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
    image: asgard-service-example
    working_dir: /app
    environment:
      - REDIS_ADDR=${REDIS_ADDR}
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
    depends_on:
      - "redis"
      - "asgard-bivrost"
  
  fullstack-postgres:
    image: postgres:latest
    container_name: full_db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    depends_on:
      - fullstack-postgres
    ports:
      - "5050:80"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    restart: unless-stopped

volumes:
  api:
  pg_data:

  redis_data:
    driver: local
  
